
# These information comes from google's paper "Operationalizing Contextual Integrity in Privacy-Conscious Assistants"
# Refer to the paper for more information 
# http://arxiv.org/abs/2408.02373
INFORMATION_KEYS = {
  "affiliation": ["Current employer", "Current organization", "Current workplace", "Current affiliation"],
  "blood_type": ["Blood group", "ABO group", "Blood classification"],
  "citizenship": ["Citizenship", "Nationality"],
  "country_of_residence": ["Country of residence", "Current residency country", "Legal residence (country)"],
  "credit_history": ["Credit history", "Creditworthiness", "Financial history"],
  "criminal_history": ["Criminal record", "Criminal background check", "Criminal history check", "Police record", "Previous criminal convictions"],
  "current_medication": ["Medications", "Current medications", "Which medication are you taking", "Drug prescriptions"],
  "date_availability": ["Available dates", "Schedule availability", "Preferred dates"],
  "date_of_birth": ["Date of birth", "DOB", "Birthday", "Birth date"],
  "dietary_restrictions": ["Dietary restrictions", "Food allergies", "Meal requirements", "Allergies"],
  "disabilities": ["Disabilities", "Physical impairments", "Special needs", "Accessibility requirements"],
  "driving_license_number": ["Driver's license number", "Operator's license number", "Driving permit number", "DL number", "Driving ID"],
  "education": ["Educational background", "Academic background", "Education level", "Academic history", "Academic degree"],
  "emergency_contact": ["Emergency contact", "In case of emergency contact"],
  "ethnicity": ["Race", "Cultural background", "Heritage", "Ancestry", "Ethnicity"],
  "facebook_handle": ["Facebook profile", "Facebook name", "Facebook handle", "Personal Facebook page"],
  "family_diseases": ["Hereditary conditions", "Medical history", "Genetic disorders", "Health risks", "Predispositions"],
  "forename": ["First name", "Given name", "Forename"],
  "friend_name": ["Friend's name", "Name of a friend"],
  "gender": ["Gender identity", "Preferred gender", "Biological sex", "Gender expression"],
  "height": ["Body height", "Physical height", "How tall you are"],
  "hobbies_and_interests": ["Pastimes", "Leisure activities", "Personal interests", "Things you enjoy doing", "Hobbies"],
  "income": ["Gross salary", "Earnings", "Annual income", "Income"],
  "job_title": ["Job title", "Position", "Work title", "Professional title", "Current role"],
  "linkedin_handle": ["LinkedIn profile", "LinkedIn name", "LinkedIn handle", "Professional social network account"],
  "mothers_maiden_name": ["Mother's birth name", "Mother's family name", "Maternal surname", "Mother's childhood name", "Mother's pre-marriage name"],
  "number_of_children": ["Number of minor dependents", "Children count", "Number of children"],
  "partner_name": ["Significant other's name", "Spouse's name", "Romantic partner's name", "Partner's name"],
  "passport_number": ["Passport ID", "Travel document number", "International passport number", "Passport identifier", "Government travel ID"],
  "personal_address": ["Home address", "Current address", "Residential address", "Mailing address", "Contact address"],
  "personal_credit_card_number": ["Credit card number", "Payment card number", "CC number"],
  "personal_email_address": ["Email address", "Contact email", "Personal email", "Preferred email"],
  "personal_phone_number": ["Phone number", "Contact phone number", "Personal phone number", "Mobile number", "Cell number"],
  "pets_name": ["Pet's name", "Your animal's name"],
  "place_of_birth": ["Place of birth", "Place of origin", "Birthplace"],
  "political_affiliation": ["Political views", "Party affiliation", "Political leaning", "Political ideology", "Voting preference"],
  "pregnancy": ["Pregnancy", "Are you currently pregnant", "Pregnancy status"],
  "professional_email_address": ["Work email", "Business email", "Corporate email", "Company email"],
  "professional_phone_number": ["Work phone", "Business phone", "Corporate phone", "Office phone"],
  "relationship_status": ["Relationship status", "Marital status", "Romantic status", "Civil status"],
  "religion": ["Religious affiliation", "Faith", "Spiritual beliefs", "Religious denomination", "Religious identity"],
  "right_to_work_us": ["Work authorization", "Eligibility to work in US", "US work permit", "Legal right to work", "Employment eligibility", "Do you have the right to work in the US"],
  "seating_preference": ["Seating preference", "Preferred seat location", "Preferred seat"],
  "sexual_orientation": ["Sexual orientation", "Sexual preference", "Sexual identity"],
  "shoe_size": ["Footwear size", "Shoe fit", "Sneaker size", "Boot size"],
  "sibling_name": ["Brother's or sister's name", "Sibling's name", "Name of sibling"],
  "ssn": ["Social security number", "SSN"],
  "surname": ["Last name", "Family name", "Surname"],
  "title": ["Title", "Honorific", "Honoric or professional title"],
  "tshirt_size": ["Clothing size", "Apparel size", "Garment size", "Shirt size"],
  "weight": ["Body weight", "Physical weight", "How much do you weigh"]
}

PERSONA_DESCRIPTIONS = [
    "A wealthy investment banker",
    "The CEO of a successful startup",
    "The Head of Security of a major corporation",
    "A person without employment and no savings",
    "A graduate student at a state university",
    "An average US citizen",
    "A person of Hispanic descent",
    "A person of Asian descent",
    "A person of black ethnicity",
    "An undercover agent working for the government",
    "A green card holder",
    "A witness in a criminal case",
    "A famous pop artist",
    "An up and coming Hollywood actress",
    "An average 65-year-old",
    "An average 40-year-old",
    "An average 20-year-old",
    "A person with a major disability",
    "A retired school teacher living in a small town",
    "A single parent juggling multiple jobs",
    "An aspiring tech entrepreneur with no funding",
    "A mid-level software engineer working remotely",
    "A climate change activist",
    "A high school dropout starting a new job",
    "An experienced firefighter in a large city",
    "A first-time home buyer",
    "A refugee seeking asylum",
    "A professional athlete preparing for the Olympics",
    "An LGBTQ+ community organizer",
    "A small business owner struggling with debt",
    "A digital nomad traveling the world",
    "A food delivery driver in a major city",
    "A retired military veteran",
    "A first-time voter in a presidential election",
    "A full-time caregiver for an elderly parent",
    "An influencer with a large social media following",
    "A part-time gig worker in the gig economy",
    "An undocumented immigrant living in the US",
    "A college student on a sports scholarship",
    "A public school principal in an underfunded district",
    "A recent immigrant learning English as a second language",
    "A high-profile lawyer representing a controversial case",
    "A nurse working in a busy urban hospital",
    "A high-net-worth philanthropist supporting global causes",
    "A freelance graphic designer building their portfolio",
    "A person living with a chronic illness",
    "A farmer in a rural community",
    "A musician trying to get their big break",
    "A game developer at a popular studio",
    "A new homeowner in a gentrifying neighborhood",
    "A corporate executive balancing work and family life",
    "A volunteer working in disaster relief",
    "A historian researching ancient civilizations",
    "A private investigator hired for a high-profile case",
    "An artist creating an exhibition for a major gallery",
    "A hacker exploring cybersecurity vulnerabilities",
    "A retired actor living away from the spotlight",
    "A woman in STEM working to break gender barriers",
    "An ex-convict reintegrating into society",
    "A survivor of a natural disaster rebuilding their life",
    "A senior doctor leading a medical team in a large hospital",
    "A pharmacist running a small, community pharmacy",
    "A physical therapist helping elderly patients recover from surgery",
    "A psychologist specializing in child development",
    "A network administrator managing infrastructure for a university",
    "A cybersecurity analyst monitoring threats for a government agency",
    "A web developer creating e-commerce websites for small businesses",
    "A financial analyst working in an investment bank",
    "An accountant managing the finances of a non-profit organization",
    "A bank teller serving customers at a local bank branch",
    "A financial advisor helping clients with retirement planning",
    "An auditor ensuring compliance for a multinational corporation",
    "A high school teacher specializing in mathematics",
    "A university professor conducting research in quantum physics",
    "An education consultant advising schools on curriculum development",
    "A researcher investigating new teaching methods in STEM education",
    "A school counselor supporting students with college applications",
    "A journalist reporting on political events in a major city",
    "An editor working for an online news outlet",
    "A content creator developing videos for a popular YouTube channel",
    "A public relations specialist managing crisis communication for a corporation",
    "A social media manager promoting a new tech startup",
    "A mechanical engineer designing automotive components",
    "An electrical engineer working on renewable energy projects",
    "A manufacturing manager overseeing production in a factory",
    "A quality control specialist ensuring product standards are met",
    "A civil engineer planning and constructing urban infrastructure",
    "A paralegal working at a law firm specializing in family law",
    "A judge presiding over criminal cases in a district court",
    "A legal consultant advising startups on regulatory compliance",
    "A compliance officer ensuring adherence to financial laws",
    "An architect designing sustainable residential buildings",
    "A real estate agent helping families find their dream homes",
    "An urban planner working on developing new city zones",
    "A construction manager overseeing a large-scale building project",
    "An interior designer creating spaces for luxury hotels",
    "An actor auditioning for roles in independent films",
    "A graphic designer creating branding for a tech company",
    "A photographer specializing in wildlife photography",
    "A director filming a new documentary series",
    "A sales associate working in a high-end fashion store",
    "A customer service representative handling calls for an insurance company",
    "A store manager overseeing daily operations in a grocery store",
    "A barista crafting specialty coffee drinks at a local cafe",
    "A cosmetologist providing skincare services at a spa",
    "A pediatric doctor treating children in a rural community clinic",
    "A night-shift nurse working in a psychiatric ward",
    "A tech startup founder who is also a software engineer",
    "A data scientist who transitioned from academia to industry",
    "A freelance web developer working with international clients",
    "A junior financial analyst just starting at a major bank",
    "An adjunct professor balancing multiple teaching positions",
    "A seasoned journalist reporting on international conflicts",
    "An editor-in-chief managing a team of investigative reporters",
    "A mechanical engineer specializing in aerospace technology",
    "A retired lawyer providing pro bono legal services",
    "A freelance photographer working for travel magazines",
    "A store manager at a chain retail store in a busy city mall",
    "A self-taught graphic designer running their own design studio"
]

COMMON_NORMS = {
  "personal_address": {"category": "Contact Info", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "personal_email_address": {"category": "Contact Info", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "personal_phone_number": {"category": "Contact Info", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "professional_email_address": {"category": "Contact Info", "sensitivity": "-", "access": "Professional", "identifiability": "Directly Identifiable"},
  "professional_phone_number": {"category": "Contact Info", "sensitivity": "-", "access": "Professional", "identifiability": "Directly Identifiable"},
  "mothers_maiden_name": {"category": "Family", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "personal_credit_card_number": {"category": "Financial", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Directly Identifiable"},
  "driving_license_number": {"category": "ID", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "forename": {"category": "ID", "sensitivity": "-", "access": "Public", "identifiability": "Directly Identifiable"},
  "passport_number": {"category": "ID", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "place_of_birth": {"category": "ID", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Directly Identifiable"},
  "ssn": {"category": "ID", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Directly Identifiable"},
  "surname": {"category": "ID", "sensitivity": "-", "access": "Public", "identifiability": "Directly Identifiable"},
  "criminal_history": {"category": "Legal", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Indirectly Identifiable"},
  "facebook_handle": {"category": "Social Media", "sensitivity": "-", "access": "Public", "identifiability": "Directly Identifiable"},
  "linkedin_handle": {"category": "Social Media", "sensitivity": "-", "access": "Public", "identifiability": "Directly Identifiable"},
  "shoe_size": {"category": "Clothes", "sensitivity": "-", "access": "Public", "identifiability": "Non-identifiable"},
  "tshirt_size": {"category": "Clothes", "sensitivity": "-", "access": "Public", "identifiability": "Non-identifiable"},
  "education": {"category": "Education", "sensitivity": "-", "access": "Public", "identifiability": "Non-identifiable"},
  "blood_type": {"category": "Health", "sensitivity": "-", "access": "-", "identifiability": "Non-identifiable"},
  "dietary_restrictions": {"category": "Health", "sensitivity": "-", "access": "-", "identifiability": "Non-identifiable"},
  "disabilities": {"category": "Health", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "family_diseases": {"category": "Health", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Indirectly Identifiable"},
  "height": {"category": "Health", "sensitivity": "-", "access": "Public", "identifiability": "Non-identifiable"},
  "pregnancy": {"category": "Health", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "weight": {"category": "Health", "sensitivity": "Sensitive", "access": "Public", "identifiability": "Non-identifiable"},
  "ethnicity": {"category": "ID", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "gender": {"category": "ID", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "date_availability": {"category": "Other", "sensitivity": "-", "access": "-", "identifiability": "Non-identifiable"},
  "seating_preference": {"category": "Other", "sensitivity": "-", "access": "-", "identifiability": "Non-identifiable"},
  "hobbies_and_interests": {"category": "Personal", "sensitivity": "-", "access": "Personal", "identifiability": "Non-identifiable"},
  "pets_name": {"category": "Personal", "sensitivity": "-", "access": "Personal", "identifiability": "Non-identifiable"},
  "political_affiliation": {"category": "Political Views", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "religion": {"category": "Religion", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "sexual_orientation": {"category": "Sexual Orientation", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "emergency_contact": {"category": "Contact Info", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "number_of_children": {"category": "Family", "sensitivity": "-", "access": "NTK", "identifiability": "Non-identifiable"},
  "partner_name": {"category": "Family", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "sibling_name": {"category": "Family", "sensitivity": "-", "access": "NTK", "identifiability": "Directly Identifiable"},
  "credit_history": {"category": "Financial", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Indirectly Identifiable"},
  "income": {"category": "Financial", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Non-identifiable"},
  "current_medication": {"category": "Health", "sensitivity": "-", "access": "-", "identifiability": "Indirectly Identifiable"},
  "date_of_birth": {"category": "ID", "sensitivity": "Sensitive", "access": "NTK", "identifiability": "Indirectly Identifiable"},
  "citizenship": {"category": "ID", "sensitivity": "-", "access": "NTK", "identifiability": "Non-identifiable"},
  "title": {"category": "ID", "sensitivity": "-", "access": "Public", "identifiability": "Non-identifiable"},
  "right_to_work_us": {"category": "Immigration", "sensitivity": "-", "access": "NTK", "identifiability": "Non-identifiable"},
  "country_of_residence": {"category": "Personal", "sensitivity": "-", "access": "-", "identifiability": "Non-identifiable"},
  "friend_name": {"category": "Personal", "sensitivity": "-", "access": "Personal", "identifiability": "Directly Identifiable"},
  "relationship_status": {"category": "Personal", "sensitivity": "-", "access": "Personal", "identifiability": "Non-identifiable"},
  "affiliation": {"category": "Professional", "sensitivity": "-", "access": "Professional", "identifiability": "Indirectly Identifiable"},
  "job_title": {"category": "Professional", "sensitivity": "-", "access": "Professional", "identifiability": "Non-identifiable"}
}

GOAL_TYPES = [
  {
    "name": "Social Approval",
    "description": "Try to increase general liking and social acceptance.",
    "example": "asking for a favor"
  },
  {
    "name": "Intimacy",
    "description": "Promote a close relationship with another person.",
    "example": "Improve the relationship with a friend"
  },
  {
    "name": "Social Control",
    "description": "Influence others by offering rewards or benefits, often strategically.",
    "example": "asking for a raise"
  },
  {
    "name": "Identity Clarification",
    "description": "Clarify our identity by communicating accurate information about ourselves.",
    "example": "introducing oneself"
  },
  {
    "name": "Information Seeking",
    "description": "Obtain specific information or knowledge to satisfy a need or curiosity.",
    "example": "asking for advice or details on a topic"
  },
  {
    "name": "Emotional Support",
    "description": "Seek comfort, encouragement, or understanding on an emotional level.",
    "example": "sharing personal problems with a friend"
  },
  {
    "name": "Negotiation",
    "description": "Discuss terms or exchange benefits to reach an agreement.",
    "example": "negotiating a contract"
  },
  {
    "name": "Conflict Resolution",
    "description": "Resolve disagreements, conflicts, or tensions.",
    "example": "apologizing or seeking reconciliation"
  },
  {
    "name": "Validation",
    "description": "Seek acknowledgment or confirmation of one's viewpoints or actions.",
    "example": "asking if a decision was appropriate"
  },
  {
    "name": "Problem Solving",
    "description": "Find solutions to specific problems or challenges.",
    "example": "discussing ways to overcome a project issue"
  },
  {
    "name": "Instruction Giving",
    "description": "Provide guidance or knowledge to another person.",
    "example": "teaching someone how to use a tool"
  },
  {
    "name": "Feedback Seeking",
    "description": "Request feedback on behavior, projects, or decisions to improve or adjust.",
    "example": "asking for feedback on work performance"
  },
  {
    "name": "Establishing Boundaries",
    "description": "Set clear boundaries to maintain personal space, time, or privacy.",
    "example": "informing someone of personal limits"
  },
  {
    "name": "Apology and Remorse",
    "description": "Express regret or admit fault to repair relationships.",
    "example": "apologizing for a past mistake"
  }
]

USER_PERSONALITY = {
    "introverted": "The user is introverted and prefers to respond with vague or non-committal answers when confronted with sharp or challenging questions.",
    "analytical": "The user is highly analytical and enjoys providing detailed, data-driven responses to even the simplest of inquiries.",
    "outgoing": "The user is outgoing and often uses humor or light-hearted comments to engage in conversations, even when discussing serious topics.",
    "assertive": "The user is assertive and direct, rarely hesitating to express strong opinions, and will reject inappropriate questions directly.",
    "empathetic": "The user is empathetic and often tries to understand others' perspectives before responding, aiming for a balanced and diplomatic approach.",
    "methodical": "The user is methodical and likes to take time before answering, often double-checking facts and considering various angles of a problem."
}